### ISSUE TITLE
Authorization: Account is not allowed to access this api

### ISSUE THREAD

**Issue by duckwaffle** [Microsoft/windows-dev-center-vsts-extension#10]
I am trying to deploy a build to the Dev Center using this extension on VSO, deploying the package via a release definition. Every time I attempt to deploy I get the following error after "Getting app information":

`Status 401: {"code":"Unauthorized","message":"Authorization: Account is not allowed to access this api"}`

I double checked all the Azure AD auth settings, and it seems to be fine, however the Azure AD that VSO is hosted on is not the same Azure AD that the Dev Center is linked to. Are there any additional steps that I need to do in order to get that to work?

**Comment by elendil326** [comment]
Hello @duckwaffle, thanks for reaching out. There is an extra step that is not detailed in the readme but you can find more information [here](https://msdn.microsoft.com/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services). In particular the missing step is this:

> **Important**
> This API can only be used for Windows Dev Center accounts that have been given permission to use the API. This permission is being enabled to developer accounts in stages, and not all accounts have this permission enabled at this time. To request earlier access, log on to the Dev Center dashboard, click Feedback at the bottom of the dashboard, select Submission API for the feedback area, and submit your request. You'll receive an email when this permission is enabled for your account.

I have a pull request to include this link in the prerequisite section of the README. After you perform the steps and receive the email it can take some time for permissions to propagate. Let us know how it goes.

**Comment by duckwaffle** [comment]
@elendil326 thanks for the info! I was under the impression that the submission API was generally available.

**Comment by elendil326** [comment]
No problem @duckwaffle. I will close the issue now. Feel free to reach out if you have more questions.
