### ISSUE TITLE
Federated credentials authentication

### ISSUE THREAD

**Issue by richardfric** [microsoft/windows-dev-center-vsts-extension#116]
I've tried to set up service connections as described [here](https://github.com/microsoft/windows-dev-center-vsts-extension/blob/master/docs/wifauth.md) but I'm not able to finish service configuration because there is no __dropdown on the right of the button "verify and save"__ and of course I got an error when trying to press the button:
![image](https://github.com/user-attachments/assets/17f6f4e2-af28-481f-8507-103ca87bbddb)

Please help.

**Comment by Zofware** [comment]
I had the same problem. I only got past that step after switching to use a real Azure subscription. 🤷

Unfortunately now I'm stuck with a 403 when the pipeline task tries to run. I plan to file a separate issue for that.

**Comment by bhagavan44** [comment]
Same issue for me too

**Comment by bhagavan44** [comment]
After providing the reader access to the application at subscription level , I am able to solve the issue

![image](https://github.com/user-attachments/assets/96b76168-b92f-46cb-a000-256f0bfda6d7)

**Comment by louis-wuitton** [comment]
Hi @richardfric, sorry to hear that you have an issue with saving the service connection. May I ask which ADO organization/product you are using? When I was trying to save the service connection there is a dropdown next to "verify and save" and when I click on that it allows me to save without verification. 

![image](https://github.com/user-attachments/assets/d6360f9a-fc21-4cf3-ba19-d40f094cda55)

**Comment by louis-wuitton** [comment]
I am interested with the ADO instance and ADO project you are using because maybe your ADO instance hasn't updated the Azure RM service connection yet. To get those information you can check your ADO URL. It would look something like https://dev.azure.com/{ADO org name}/{ADO project name}/...

**Comment by richardfric** [comment]
> I am interested with the ADO instance and ADO project you are using because maybe your ADO instance hasn't updated the Azure RM service connection yet. To get those information you can check your ADO URL. It would look something like [https://dev.azure.com/{ADO](https://dev.azure.com/%7BADO) org name}/{ADO project name}/...

Yes, URL has exactly the format you mentioned but I won't share it here in public. What does it mean that Azure RM service isn't updated yet?
Should I contact MS support or can I somehow to do it myself?

**Comment by louis-wuitton** [comment]
Azure RM is a type of service connection. In my case, I am on Office ADO org and CLE project, and when I create an Azure RM type service connection it allows me to click on a drop down next to verify and save and save without verification (See below screenshot). I am not sure if your ADO organization allows you to do that. If not then you would need to provide a real Azure subscription and make sure your App registration has access to it.

![Image](https://github.com/user-attachments/assets/b867dc49-baae-449e-832e-44570abc3c42)

**Comment by richardfric** [comment]
> Azure RM is a type of service connection. In my case, I am on Office ADO org and CLE project, and when I create an Azure RM type service connection it allows me to click on a drop down next to verify and save and save without verification (See below screenshot). I am not sure if your ADO organization allows you to do that. If not then you would need to provide a real Azure subscription and make sure your App registration has access to it.
> 
> ![Image](https://github.com/user-attachments/assets/b867dc49-baae-449e-832e-44570abc3c42)

Thanks for explanation. It would be helpful to add also App registration use case to the guide. I'm closing this issue for now.

**Comment by softworkz** [comment]
Is there anybody who managed to get the v3 tasks for MS Store submission actually working?
