### ISSUE TITLE
Updating "Version Notes"

### ISSUE THREAD

**Issue by softworkz** [microsoft/windows-dev-center-vsts-extension#120]
The new "Version Notes" display in the store app is nice. As far as I've understood, these can be updated in the store portal by editing the "What's new" field.

Is it possible to update the version notes information with the DevOps store tasks?

Thanks

**Comment by louis-wuitton** [comment]
Yes. Adding the "What's new" notes as metadata is available on the extension and this doc shows how to add it to extension. https://github.com/microsoft/windows-dev-center-vsts-extension/blob/master/docs/usage.md#metadata-update

**Comment by softworkz** [comment]
Ah, great, thank you very much!
