### ISSUE TITLE
Submission fails with invalid AllowTargetFutureDeviceFamilies

### ISSUE THREAD

**Issue by nickward13** [Microsoft/windows-dev-center-vsts-extension#22]
When submitting my app to the Window Store using the VSTS extension, the store returns a 400 error with the following message, after the "Updating submission..." step: "AllowTargetFutureDeviceFamilies was not updated with all supported platform(s): [Desktop, Mobile, Xbox, Holographic]".  Can you suggest steps we can take to fix this?

**Comment by ChristopheLav** [comment]
Hello. You can send an update of your application in the Windows Store Developer portal (without any change or only a white space in description). After that, the field "AllowTargetFutureDeviceFamilies" is automatically set to a default value properly. I think it's a new field (from a few weeks now) and it's provisionned only with an description update on the Windows Store Developer portal. The VSTS extension reuse actual value for this field and not automatically use the default value when there no value is set.

**Comment by elendil326** [comment]
Hello @nickward13, as @ChristopheLav mentioned, neither the extension nor the API populate new fields when these are added, such as values in the AllowTargetFutureDeviceFamilies mapping. A simple workaround for this is to create a manual submission through the Web Portal without any change as @ChristopheLav describes above.

Let us know how it goes and feel free to close the issue if you are unblocked.

**Comment by nickward13** [comment]
Thanks @ChristopheLav and @elendil326 - greatly appreciated.  Trying it again now.

**Comment by nickward13** [comment]
Confirming - this has resolved the error and the submission is continuing from VSTS.  Many thanks again!
