### ISSUE TITLE
Unhandled: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Odonno** [Microsoft/windows-dev-center-vsts-extension#33]
![image](https://cloud.githubusercontent.com/assets/6053067/26024306/2f9b883a-37cf-11e7-9ef2-f7c5041c914b.png)

**Comment by zurdev** [comment]
There seems to be an issue creating the zip file for the flight submission. From the error it looks like the agent executing the task doesn't have read access to the packages you're trying to publish.
Could you enable debug output, by adding variable system.debug equals to true in your release/build definition and share your log after repro?
Sorry for the inconvenience.

**Comment by Odonno** [comment]
Of course. By the way, the current version of the package in the Store is 0.1.0.0 and the build version that I want to upload is 0.1.36.0

![sans titre](https://cloud.githubusercontent.com/assets/6053067/26168808/c3646766-3b3b-11e7-9d27-c1ecc1142d34.png)

**Comment by zurdev** [comment]
The package path should resolve to a full path to appxbundle file, the debug print indicates that your package path is d:/a/1/s, which is a folder not a file.

**Comment by Odonno** [comment]
@zurdev I thought there was an automatic detection of the appxbundle. I'll change the path and see if it works.

**Comment by zurdev** [comment]
You could use minimatch pattern in the package path, e.g. $(Agent.ReleaseDirectory)/**/*.appxbundle

**Comment by Odonno** [comment]
Ok, I have a different error now.

```
Errors occurred in request
	[InvalidParameterValue]  Package acceptance validation error: You cannot submit pre-compiled .NET Native packages. Please upload the Store appxupload file and try again. http://go.microsoft.com/fwlink/?LinkId=797528
Submission status for "***********" failed with CommitFailed
Reported errors: 
InvalidParameterValue: Package acceptance validation error: You cannot submit pre-compiled .NET Native packages. Please upload the Store appxupload file and try again. http://go.microsoft.com/fwlink/?LinkId=797528
Error: Commit failed
    at d:\a\_tasks\store
```

Did I miss something?

**Comment by zurdev** [comment]
If that's your first submission to the store, it should be done from Dev Center, see extension [prerequisites](https://marketplace.visualstudio.com/items?itemName=MS-RDX-MRO.windows-store-publish&targetId=a2fba5bb-e91f-4218-8d9f-3ba6468216b4).
The pre-compiled .NET Native packages could be the result of your build configuration in Visual Studio. Checkout this [post ](https://blogs.msdn.microsoft.com/visualstudioalm/2015/07/29/debugging-net-native-windows-universal-apps/) on how to disable .NET Native complication tool chain.

**Comment by Odonno** [comment]
I tried the other extension (https://marketplace.visualstudio.com/items?itemName=davesmits.windows-store-automation) and it worked fine. I don't know why. The only thing that change is that they use `appxupload` instead of `appxbundle`.

**Comment by zurdev** [comment]
Glad you were able to find a workaround. For troubleshooting the appxbundle validation error, we will need more information:

1. How do you package your appxupload? using Visual Studio or manually creating the zip file?

**Comment by elendil326** [comment]
Closing due to issue being too old. @Odonno, feel free to reopen the issue if you are still having issues.
