### ISSUE TITLE
Windows Store - Flight:  Advanced Options > Delete Packages option not working

### ISSUE THREAD

**Issue by apwillies** [Microsoft/windows-dev-center-vsts-extension#41]
I’m using your Release Task on our TFS server to publish our app to the Windows Store. I’m using the “Flight” version. It all works great – except for one thing. The **Advanced Options** > **Delete Packages** option doesn’t seem to work. The “info” tip for this says “Delete old unnecessary packages from the flight group you are submitting to.” However, our appxupload files keep on accumulating on the Windows Store.

**Comment by zurdev** [comment]
We'd be happy to help you look into this issue. Please enable debug logging by adding release variable system.debug with value set to true. After you repro, you may post the task log in this thread, so we can take a look.
Please note that the number of packages to keep is per unique Target Device Family and Target Platform.

**Comment by apwillies** [comment]
Hi @zurdev I'm attaching the Release Logs from our most recent build. 

> the number of packages to keep is per unique Target Device Family and Target Platform
We are creating only a UWP app, so I expect that as I upload a new UWP appxbundle, the old one will be removed. It cannot be downloaded anyway because the new one supersedes it, so there's no point in keeping it. However, note the jpg file attached: bundles are just accumulating on the Store.

![windowsstore-flight](https://user-images.githubusercontent.com/26043565/29429508-eb802198-835e-11e7-94b3-ff07a40bef40.jpg)

[ReleaseLogs_235.zip](https://github.com/Microsoft/windows-dev-center-vsts-extension/files/1232305/ReleaseLogs_235.zip)

**Comment by zurdev** [comment]
Thanks for taking the time to repro and for sharing the log.
It looks like a bug, when numberOfPackagesToKeep is set to 0, the deletion of packages is skipped. As a temporary workaround, please set the value to 1, it will delete all the old packages, except for the latest one.

**Comment by zurdev** [comment]
#43

**Comment by apwillies** [comment]
@zurdev Thanks for the quick and decisive response! Our automated push to the Store starts at 11:50 EST, so I'll make the change now and confirm that the old builds are cleaned up this afternoon.
