### ISSUE TITLE
Publishing Apps to the Win Store using the TFS Release Management Task

### ISSUE THREAD

**Issue by jaitad19** [Microsoft/windows-dev-center-vsts-extension#44]
We have included the 'Publish' task (that comes with the Windows Store Marketplace extension https://marketplace.visualstudio.com/items?itemName=MS-RDX-MRO.windows-store-publish) as part of the TFS release process to automatically publish the App updates to the store.
The task is successfully making the Submissions. However the packages are not getting updated as part of the Submission process. 
﻿

**Comment by zurdev** [comment]
We will need more information to help you debug this issue. Could you send us the task log?
Enable debug logging for easier troubleshooting, set environment variable System.Debug to true in your release definition and try to repro.
Sorry for the inconvenience.
