### ISSUE TITLE
Flighted / Private Submissions

### ISSUE THREAD

**Issue by drewkg** [Microsoft/windows-dev-center-vsts-extension#52]
Any chance of an update to support flighted / private submissions?

**Comment by elendil326** [comment]
@drewkg, are you referring to [this](https://stackoverflow.com/questions/48499524/error-base-is-not-a-valid-priceid-for-base-price-when-trying-to-deploy-a-mi) issue? The particular issue has been fixed in the store API already.

**Comment by drewkg** [comment]
The store can accept flighted submissions or private submissions (to named users) however the Microsoft task does not support making these submissions from VSTS, there are other third party extensions that support some of the functionality or I can write my own but would prefer a Microsoft supported extension.

**Comment by elendil326** [comment]
I'm still not 100% sure I understand what you mean by private submissions. After talking with the store team, I found out that the following type of apps are not supported by the API. Is your scenario one of the following?

- [LOB app](https://docs.microsoft.com/en-us/windows/uwp/publish/distribute-lob-apps-to-enterprises)
- [Private audience](https://docs.microsoft.com/en-us/windows/uwp/publish/beta-testing-and-targeted-distribution#private-audience)
- [Content Isolation](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/xbox-live-sandboxes)

**Comment by elendil326** [comment]
Closing this issue. Feel free to comment or re-open if you require further assitance.
