### ISSUE TITLE
Cannot create flight package

### ISSUE THREAD

**Issue by tnsturm** [Microsoft/windows-dev-center-vsts-extension#57]
I'm experiencing a strange behavior:

I'm trying to set up publishing a flight package through VSTS. Connection, Authentification etc works fine.

In the Field "_Flight name_" I am entering a flight name like I would do in Dev Center "_Package flight name_".

When I now trigger a publish, VSTS shows error message: "_**No flight with name 3.3.0**_".

I then thought because of this this statement in docu: "_This task allows you to publish your app **to specified flight** on the Store by creating a submission on Dev Center_" that i have to create the flight package in Dev Center prior to publishing through VSTS.
Error message now is: "_Ingestion API can only update, delete, and commit submissions that are created through the API. Please delete the current in-progress submission and create one using the API_"

I'm now somewhat lost, I can't create a flight, but I can also not publish to a previously created flight. 

Furthermore, there is this line in Documentation:
"_Flight name (Text, required) - Friendly name of the flight **group** (as seen on the Dev Center) that you want to update the submission for._"

OK, Flight Group... I tried to put the name of the group of testers ("_Testers_") as defined in Dev Center into the field "Flight name", but that leads again to Error: "_**No flight with name Testers**_"

Please help!

Best Regards
Torsten

**Comment by elendil326** [comment]
Thanks for reporting this issue @tnsturm . Based on what you describe, it looks like when you create manually the submission through dev center, you try to create a new one from the extension without letting the first one complete, that is why you hit the error "_Ingestion API can only update, delete, and commit submissions that are created through the API._". Please create the submission manually in Dev Center for the flight, submit it and let it finish. Then you should be able to use the extension for future submissions.

Let me know how it goes. Happy to clarify further if needed.

**Comment by elendil326** [comment]
I'm closing this issue since it is not related to the code.

**Comment by jzoooneee** [comment]
reopening this.

as per @tnsturm, i believe this was done through azure devops. I too am having the same issue.

I made sure I have no flight packages on pending in partner center. and have test group created.

I tried entering new flight name but threw this error : No flight with name "test app"

as suggested to use flight group name. threw this error : "Ingestion API can only update, delete, and commit submissions that are created through the API. Please delete the current in-progress submission and create one using the API"

![image](https://user-images.githubusercontent.com/31412448/92009857-19235c80-ed17-11ea-8be4-034186819096.png)

any thoughts?

**Comment by louis-wuitton** [comment]
Hi @jzoooneee , please make sure the flight name you put matches exactly to the flight name it appears on the partner center. You can also give it a try to create submission on the flight directly on partner center, let it run and finish, as suggested before.

**Comment by jzoooneee** [comment]
there is no specified flight name in partner center. I would have to create a new package flight in order for it to be available.. However, when I do that, I get this error.


`2020-09-02T17:08:01.2191797Z ##[error]Status 400: {"code":"InvalidOperation","data":[],"details":[],"message":"Ingestion API can only update, delete, and commit submissions that are created through the API. Please delete the current in-progress submission and create one using the API","source":"Ingestion Api","target":"applicationSubmission"} CorrelationId: e6ff5c4b-4037-48df-a099-1e2565e633a2`

**Comment by louis-wuitton** [comment]
Do you see the error message on partner center? Also do you see any submission on partner center regardless of flights?

**Comment by jzoooneee** [comment]
No i don't see any error. And yes there's a pending submission to publish to store.

![image](https://user-images.githubusercontent.com/31412448/92017165-5e4c8c00-ed21-11ea-8f64-4002a333917d.png)

**Comment by louis-wuitton** [comment]
Emm give it a try to delete that pending submission, then create a new package flight.

**Comment by louis-wuitton** [comment]
Did you create a new package flight called "test app"?

**Comment by jzoooneee** [comment]
I did, that was the last comment i mentioned 
https://github.com/microsoft/windows-dev-center-vsts-extension/issues/57#issuecomment-685874242

**Comment by louis-wuitton** [comment]
When I saw your screenshot I didn't see a flight called "test app" created. Was that because you got this error?
 
2020-09-02T17:08:01.2191797Z ##[error]Status 400: {"code":"InvalidOperation","data":[],"details":[],"message":"Ingestion API can only update, delete, and commit submissions that are created through the API. Please delete the current in-progress submission and create one using the API","source":"Ingestion Api","target":"applicationSubmission"} CorrelationId: e6ff5c4b-4037-48df-a099-1e2565e633a2

- [ ]

**Comment by jzoooneee** [comment]
Yes correct. I deleted the flight package "test app" because it threw that InvalidOperation error.

**Comment by louis-wuitton** [comment]
From this comment: https://github.com/microsoft/windows-dev-center-vsts-extension/issues/57#issuecomment-415452885

I think what you can give it a try is to create the flight "test app", make sure it appears on partner center, then create a submission directly on partner center to the test app flight. There is no need to run the extension throughout this process. 

Then if you can successfully submit a submission on partner center, then give it a try on the extension again.

**Comment by gentledepp** [comment]
Why is this issue closed? It is nearly 2022 and I still have this issue.
Or is this library deprecated just like UWP?

Our goal was to run a release in azure devops for our UWP app and let it create a new package flight named after `$(Build.BuildNumber)`  (i.e. 2021121.0) for our flight group "Beta testers"

However, no matter what I try, this does not work.
1. I used "Beta testers" as friendly name
Result: 
![image](https://user-images.githubusercontent.com/1175751/144220821-98331624-3318-469c-83ae-3d22993da485.png)

2. I configured "$(Build.BuildNumber)" as friendly name
Result:
![image](https://user-images.githubusercontent.com/1175751/144221292-afe06a52-9f2b-430d-973d-e8b9036d5e8f.png)

Sure there isn't! I want it to create a new package flight **without** me having to manually upload the artifacts.

3. I add a new package flight manually and call it "2.2112.1.0" 
![image](https://user-images.githubusercontent.com/1175751/144221379-92c8eac3-e7be-460b-9c5d-6555b3deac6b.png)
Result:
![image](https://user-images.githubusercontent.com/1175751/144221670-066b0b5e-5ffb-4436-a2a1-81fd48f8ca43.png)

4... changed the task to "delete pending submissions":
```yaml
steps:
- task: MS-RDX-MRO.windows-store-publish.flight-task.store-flight@0
  displayName: 'Internal test flight'
  inputs:
    serviceEndpoint: 'Windows Dev Center'
    appId: THIS-IS-A-SECRET
    flightName: '$(Build.BuildNumber)'
    packagePath: '**/*.msixupload'
    force: true
```
Result:
![image](https://user-images.githubusercontent.com/1175751/144222178-cce89dd6-42e2-4247-a6a6-5335a7dd4ac1.png)


**Please delete the current in-progress submission and create one using the API"** - HOW? 😳

How on earth shall we automate our build then? 
I cannot find any helpful instructions on that topic.
Do we need to actually use different APIs? 
Please point me in the right direction!
