### ISSUE TITLE
No longer work

### ISSUE THREAD

**Issue by anhoavu** [Microsoft/windows-dev-center-vsts-extension#60]
It fails with the following error:

    Status 401: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: ea6e48c7-6985-4e5f-9c06-58120cb10200\r\nCorrelation ID: 9594e0dd-1da8-40cc-8523-01b8427ba360\r\nTimestamp: 2018-11-16 18:53:43Z","error_codes":[70002,50012],"timestamp":"2018-11-16 18:53:43Z","trace_id":"ea6e48c7-6985-4e5f-9c06-58120cb10200","correlation_id":"9594e0dd-1da8-40cc-8523-01b8427ba360"}

It worked perfectly in my previous release on 6/29/2018. (I did not make any change to the service connection.) Updating the service connection doesn't make it work. Could it be related to Microsoft migration to Azure?

**Comment by ChristopheLav** [comment]
I made a deployment successfully today. Maybe your client secret is expired? It's necessary to renew it each year from the Azure Portal.

**Comment by anhoavu** [comment]
@ChristopheLav I didn't know that one needs to renew the client secret every year since most other OAuth2 application doesn't require that. I think it should be pointed out in the documentation.

**Comment by elendil326** [comment]
Closing this issue as resolved. Feel free to open it if the issue still persists.
