### ISSUE TITLE
Can the extension support asynchronous submissions, or return earlier?

### ISSUE THREAD

**Issue by apwillies** [Microsoft/windows-dev-center-vsts-extension#61]
Here's the problem: Once submitted, the app can sit "in certification" in the Windows Store anything from 1 to 72 hours to approve a build. The binaries are uploaded to the store fairly quickly, and then the windows-dev-center-vsts-extension just waits for the Store to move to the "publishing" phase. If the app sits a long time "in certification," our build server is locked up the whole time and is  unable to do anything else. In these situations, we have to Cancel the release to unblock the build server. Even though we are only submitting to our Alpha flight and not releasing to the public, the Windows Store approval workflow doesn't seem to care and could take days to approve the submission. 

_Can the extension be asynchronous? Or can it return once the submission is complete, and not wait until the "publishing" phase?_

There was a similar issue [here](https://github.com/Microsoft/windows-dev-center-vsts-extension/issues/58) - but that seems to have been sparked during a slow phase on the Store.

**Comment by zurdev** [comment]
You can check 'Skip polling' under Advanced Options:
Skip polling submission after committing it to Dev Center. Warning: if you check this box, you will not see errors, if any, that your submission may run into. You will have to manually check the status of your submission in Dev Center.

**Comment by elendil326** [comment]
Closing this issue as resolved. Feel free to comment or reopen if this solution doesn't satisfy your needs.
