### ISSUE TITLE
UnknownInternalFailure

### ISSUE THREAD

**Issue by ridomin** [microsoft/windows-dev-center-vsts-extension#62]
My submissions fail with

```
2019-01-08T06:07:52.4899319Z 68e5ca97-05bb-4771-8a2d-e82eb933d07c exists true
2019-01-08T06:07:52.4903891Z Authenticating...
2019-01-08T06:07:52.4904119Z Authenticating with server...
2019-01-08T06:07:52.8102996Z Obtaining app information...
2019-01-08T06:07:54.8924745Z Creating submission...
2019-01-08T06:07:55.5173739Z ##[error]Status 500: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"} CorrelationId: d5a58222-70a2-4739-b8fc-9711d8b15581
```

How can I diagnose this issue?

**Comment by ChristopheLav** [comment]
I got this same error yesterday, I have restart my deployment after a few minutes and it was in success.

**Comment by ridomin** [comment]
@elendil326 can you check what's wrong from the error correlation id?

**Comment by rzippo** [comment]
Having the same issue.

**Comment by rido-min** [comment]
any updates?

**Comment by rzippo** [comment]
In my case, I found the error was using Package/Identity/Name instead of Store ID as `appId`.
I think reporting UnknownInternalFailure also when there are configuration issues, and not just server-side issues, is confusing.

**Comment by IsmailHassani** [comment]
I started to get the same exceptions. (flight and non-flight). I'm already using appId as StoreId.
The strange thing is that het package is actually submitted only I have to manually "Submit to Store" to finish the submission.

```
Status 500: {
"code":"InternalServerError",
"data":[],
"details":[],
"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},
"message":"An internal server error occurred while processing the operation.",
"source":"Ingestion Api"} 
CorrelationId: e39dd1b2-ebe3-44be-b226-2cbccf5d4fee
```

**Comment by IsmailHassani** [comment]
It seems that the update is created in Dev Center without the updated packages. So manually submitting it to the store is not sufficient.
Any news regarding this issue?

**Comment by IsmailHassani** [comment]
Another error I frequently noticed:
```
Operation failed with Error {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"40.117.96.136","port":443}
```

**Comment by IsmailHassani** [comment]
Issue has been solved.

> What I heard back from the Submission API team:
The user's app has ARM64 packages, and that package type had not been supported by the API.
They just made a fix to add support for that package type, and the fix should be deployed to the live site within the next couple hours. So, the suggestion is to simply try again in another couple hours and hopefully you should be unblocked. Please report back either way.
