### ISSUE TITLE
Active Directory Install Setup Docs Confusing?!

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/windows-dev-center-vsts-extension#64]
The documentation for installing Active Directory and getting the Client ID & Secret is very confusing.

I have added a new AD created from this documentation
https://docs.microsoft.com/en-gb/windows/uwp/publish/associate-azure-ad-with-partner-center#create-a-brand-new-azure-ad-to-associate-with-your-partner-center-account

I have associated the new Active Directory in Windows Partner Center & also inside Azure DevOps.

I have no idea how to find out these details to configure the connection in Azure DevOps.
Can you point me in the right direction on how to find this information, as I imagine the UI of the sites may have changed since the original documentation was written.

I have found this page in the MS DevCenter portal about adding a New Azure AD Application but again I have no idea on what the Reply URL would be here?!

![image](https://user-images.githubusercontent.com/1389894/54489137-0b6ae480-48a1-11e9-80bf-3c9eb859401e.png)

**Comment by MatthewSteeples** [comment]
You can put any value in those boxes. They would only be used if users were involved in the authentication of your app

**Comment by elendil326** [comment]
Hi @warrenbuckley,

Sorry for the delayed response. The links in our readme file seem to be outdated. Have you tried following these steps: https://docs.microsoft.com/en-gb/windows/uwp/publish/add-users-groups-and-azure-ad-applications#create-a-new-azure-ad-application-account-in-your-organizations-directory-and-add-it-to-your-partner-center-account

**Comment by warrenbuckley** [comment]
I have just seen your response/s and will take a look later today to see if I can get this setup and working.
If I get stuck expect more questions @elendil326 & @MatthewSteeples

**Comment by warrenbuckley** [comment]
OK that looks like it has worked - but I would highly recommend you update the documentation and guidance on this repo so its more in sync and avoids confusion.

I get that I do not need a reply URL etc @MatthewSteeples but it would be good to outline in the docs for this repo :)

**Comment by MatthewSteeples** [comment]
@warrenbuckley agree with you 100% there. I'm not a Microsoft employee so was just trying to get this configured myself! I know that docs accept pull requests but I wasn't sure if they'd accept one basically rewriting the instructions
