### ISSUE TITLE
Can the Task use the actual names of the properties?

### ISSUE THREAD

**Issue by mandalorianbob** [microsoft/windows-dev-center-vsts-extension#66]
Right now the Task uses one of two properties to identify the package.
"Application Id"
and
"Package Name"

The "Application Id" is **not** the application id but is instead the Store Id (or Big Id).
The Package Name is **not** the Package Name, and I don't know what it is. Trying to use the Package Name returns 403. (I thought it might the Package Family Name, which is different, but didn't get a chance to try it.)

Can these names be changed to what they **actually** are, and perhaps some kind of tooltip or information added as to where we can find these properties?

Oh also, 403 seems like the wrong error code to return if you screw up the ID of the package. The correct code for when you cannot find a resource is 404. I assume 403 is given because I do not have permissions to "create" an otherwise "uknown" package. At any rate, given the actual solution to the problem (correcting the ID) - 404 is significantly more clear. Or at the very least, a 403 with an explanation that the package cannot be identified.

**Comment by elendil326** [comment]
Hello @mandalorianbob,

Sorry for the confusion. In regards the Application Id. The Developer Center used to show this information in the top left of the application overview page. You can still see in the [documentation of the API](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-app-submissions) how this parameter is referred to as "applicationId". This extension is following the naming convention of the API itself as it is the wrapper on top of it for CI in ADO.

In regards the "Package Name", I believe you meant to say "Application Name". If that is the case, the [documentation of this extension](https://github.com/microsoft/windows-dev-center-vsts-extension/issues/66) states as the app primary name which is visible on the app's page on Dev Center.
