### ISSUE TITLE
Support wildcards in package path

### ISSUE THREAD

**Issue by baumerik** [Microsoft/windows-dev-center-vsts-extension#8]
Hi I need to specify a wild card path like "drop*.appxupload" because in my app names I include version number and build numbers.

Thx 
Erik

**Comment by elendil326** [comment]
Thanks for raising this issue @baumerik , I have labeled it as "suggestion" while we look into it. Will keep you updated.

Thanks

**Comment by elendil326** [comment]
This is supported already, so closing this thread.
