### ISSUE TITLE
Stauts 409: Invalid State

### ISSUE THREAD

**Issue by michelebonomelli** [microsoft/windows-dev-center-vsts-extension#80]
After a first succesful submission to store, I'm always getting status 409: Invalid State:

##[error]Status 409: {"code":"InvalidState","data":[],"details":[],"message":"Create submission failed, status code Conflict, reason phrase Conflict","source":"Ingestion Api","target":"submission"} CorrelationId: b46aea06-c1d7-43e8-916c-04785abd4b38

**Comment by Trolldemorted** [comment]
What did you do to resolve this issue?

**Comment by edparitor** [comment]
Just in case other people get this error: There's a checkbox that says 'Delete pending submissions' 
![image](https://user-images.githubusercontent.com/68241268/104438484-f38d4600-5587-11eb-98cb-665453a78df8.png)
