### ISSUE TITLE
Won't upload StoreLogo9x16 image

### ISSUE THREAD

**Issue by tesar-tech** [microsoft/windows-dev-center-vsts-extension#83]
So. I set up pipeline and almost everything works just fine, screenshots upload included. 

I need to also update `StoreLogo9x16` image, but it won't appear in a store submission.

This is folder structure I tried (see `attempt 1` and `attempt 2`):

```
appMetadata
\---en-us
    \---baseListing
        |   metadata.json
        |
        \---images
            |   StoreLogo9x16.png //attempt 1
            |
            +---Screenshot
            |       screenshot01.metadata.json
            |       screenshot01.png
            |       screenshot02.metadata.json
            |       screenshot02.png
            |
            \---StoreLogo9x16
                    StoreLogo9x16.png //attempt 2
```
I also tried adding json metadata file. But without success. 
Am I doing something wrong here?

You can see the project here: https://github.com/tesar-tech/StoreUp/tree/master/NoApp/Store/appMetadata/en-us/baseListing

**Comment by tesar-tech** [comment]
It is probably caused by missing values in `imageType` array (https://github.com/microsoft/windows-dev-center-vsts-extension/blob/master/tasks/store-publish/publish.ts#L19).
`StoreLogo9x16` and `StoreLogoSquare` are missing. Values are taken from [here](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-app-submissions?redirectedfrom=MSDN#image-object).

Could someone look at this?

**Comment by louis-wuitton** [comment]
Hi @tesar-tech , sorry for the delay. I looked into the extension and you are right, the supported imageType array is outdated. I updated imageType array for the extension so check to see if it works for you. Thanks!

**Comment by louis-wuitton** [comment]
Created PR to address this issue: #88

**Comment by tesar-tech** [comment]
It work's now. Thanks.
