### ISSUE TITLE
Flight to Alpha - Status 500

### ISSUE THREAD

**Issue by dpaulino** [microsoft/windows-dev-center-vsts-extension#91]
I am getting this error:

> 2020-07-08T05:49:53.0677992Z ##[error]Status 500: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"} CorrelationId: de738723-b7ce-40f2-9c82-bdbaf84f5639

Is it just an issue with the dev center APIs? And if so, where can I go to report this issue?

**Comment by louis-wuitton** [comment]
This is an issue with the Windows Store Api. I have contact with with them so I can report this issue.

**Comment by dpaulino** [comment]
@louis-wuitton great thanks for contacting them. Please let me know if you hear any progress

**Comment by dpaulino** [comment]
It looks like the api is working again. Closing this ticket.
