### ISSUE TITLE
Azure DevOps, Windows Store Publish Tasks service connection issue.

### ISSUE THREAD

**Issue by arctouch-williamrodriguez** [microsoft/windows-dev-center-vsts-extension#92]
Hi,

we are building a UWP app and for a couple of days, we are trying to use the Windows Store Publish Tasks from Microsoft (https://marketplace.visualstudio.com/items?itemName=MS-RDX-MRO.windows-store-publish) to automate our release pipeline using Azure DevOps.

There are two main issues:

- Since the last update, there are two new fields that we don't know what information we need to fill in: 
`Username` and `Password`, where we can find that information? Which account is? This is secure?
- The documents are very outdated, its really hard to find any meaningful information about the setup of this task;

Please if you can help us!

Thanks in advance.

**Comment by pulla2908** [comment]
@arctouch-williamrodriguez 

See [this](https://github.com/microsoft/windows-dev-center-vsts-extension/issues/78#issuecomment-657005933) about the new 2 fields. 

Yes, it would be great to update the documentation.

**Comment by arctouch-williamrodriguez** [comment]
Thanks @pulla2908 it worked!
